# Alpine (apk)
FROM alpine:3.20
RUN apk add --no-cache \
    curl \
    sudo \
    lsb-release \
    gnupg \
    ca-certificates \
    build-base \
    git
WORKDIR /app
COPY . .
RUN cd multitool && go build -o mt
ENTRYPOINT ["/app/multitool/mt"]
