# Ubuntu (apt)
FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    curl \
    sudo \
    lsb-release \
    gnupg \
    ca-certificates \
    build-essential \
    git
WORKDIR /app
COPY . .
RUN cd multitool && go build -o mt
ENTRYPOINT ["/app/multitool/mt"]
