version: 2

run:
  tests: true
  timeout: 5m

linters:
  enable:
    - govet
    - gofmt
    - revive
    - staticcheck
    - unused
    - errcheck
    - gosimple
    - ineffassign
    - structcheck
    - varcheck
