[run]
tests = true
timeout = "5m"

[linters]
enable = [
  "govet",
  "gofmt",
  "revive",
  "staticcheck",
  "unused",
  "errcheck",
  "gosimple",
  "ineffassign",
  "structcheck",
  "typecheck",
  "varcheck"
]
