name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run Go tests
        run: go test ./... -v
      - name: Run shell scripts (end-to-end)
        run: |
          chmod +x generator/end2end_test.sh || true
          chmod +x generator/end2end_multitool_test.sh || true
          ./generator/end2end_test.sh || echo 'end2end_test.sh failed'
          ./generator/end2end_multitool_test.sh || echo 'end2end_multitool_test.sh failed'
        shell: bash
      - name: Start sim-server (background)
        run: |
          nohup go run sim-server/main.go > sim-server.log 2>&1 &
          for i in {1..10}; do
            curl --fail http://localhost:8080/api/v1/status && break
            sleep 2
          done
      - name: Run new end-to-end API tests
        run: |
          chmod +x scripts/end2end_api_test.sh
          bash scripts/end2end_api_test.sh
        env:
          API_KEY: dev-secret-key
          BASE_URL: http://localhost:8080
